Tengda-He/kibana

test/functional/apps/visualize/_tile_map.js

**Issue:** When map is zoomed in to the max level, a pop up warning is displayed. However after the warning is clicked and closed by the functional test, it again zooms in consequently triggering the warning. Since this functional test checks for the warning to be closed, the functional test fails. 
**Solution:** this PR removes the code that zooms in again/redundantly. 
Image of tile map zoomed in with warning showing up:
***NOTE:*** The tile map has been updated and this test case has been removed in the future PR: https://github.com/elastic/kibana/pull/105326

Fix max zoom warning behavior 

---

src/dev/build/lib/scan_copy.test.ts

This test expects windows platform to output code 644. This passes when testing on local machine, however, gives a flaky result on jenkins. The proposal is to skip this test.

Skipped flaky test

---

Jenkinsfile

Even though all tests pass, Jenkins test job fails due to invalid jUnit path. This PR fixes the error. A jenkins job was run to verify it successfully resolves issue.
Closes issue #33 
Jenkins job: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs7.7.1/165/

Fix for functional test jUnit path

---

src/cli_plugin/lib/error_if_x_pack.test.js
src/cli_plugin/lib/is_oss.test.js
src/cli_plugin/remove/remove.test.js
src/dev/build/lib/scan_copy.test.ts

> est Tests.src/dev/build/lib.copies files and directories from source to dest, including dot files, creating dest if necessary, respecting mode (from src_dev_build_lib_scan_copy.test.ts) 
This flaky test was identified in PR: #28. It expects "Is_windows" to be either 644 or 666. This works on local machine and outputs 644. However, the output is flaky on Jenkins and results in "664". This test file has also been removed in branch 7.10
x-pack files/directories removed therefore the other failed tests need to be skipped.

Unit Tests Skipped

---

Jenkinsfile

Jest-junit requires node >= 10, while bfs 6.5.4 uses node v8.19.0. This PR downgrades jest-junit to v10.0.0 to be complacent to node v8.
jest-junit v10.0.0 node compatibility: https://github.com/jest-community/jest-junit/blob/87e3413fce60dfd420f78aa0b6a47cf98600134a/package.json#L10
Closes issue #49

downgrade jest-junit to 10.0.0

---

src/cli_plugin/lib/error_if_x_pack.test.js
src/cli_plugin/lib/is_oss.test.js
src/cli_plugin/remove/remove.test.js
src/dev/typescript/projects.ts

This PR fixes the following x-pack related test failures:
1. Removes `x-pack/tsconfig.json` and `x-pack/test/(*|**)` from root directory. This was causing jenkins unit failure by adding x-pack tsconfig.json file to test files. 
- **Jenkins Unit Test Failure Report:** https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4/7/console
2. Skips x-pack related tests
Closes issue #51

Fix x-pack related test failures

---

Jenkinsfile
dockerfile

Chrome v94 requires node >= 10.17.0, however, current node version is 10.15.2. This PR downgrades chrome to v89, which supports node 10.15.2. 
Closes #53

downgrade chrome v94 --> v89

---

Jenkinsfile

This PR fixes the naming convention of the docker image. In jenkins job number 17 for bfs7.7.1 and bfs 6.5.4, two separate jobs but with the same name "test-image:17" were concurrently ran. This caused failure in the node environment because the jenkins job for bfs7.7.1 and bfs6.5.4 was pointing to the same docker container "test-image:17"
bfs7.7.1 job 17: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs7.7.1/17/
bfs6.5.4 job 17: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4/17/

Change docker image naming convention for BFS7.4.2

---

Jenkinsfile

This PR fixes the naming convention of the docker image. In jenkins job number 17 for bfs7.7.1 and bfs 6.5.4, two separate jobs but with the same name "test-image:17" were concurrently ran. This caused failure in the node environment because the jenkins job for bfs7.7.1 and bfs6.5.4 was pointing to the same docker container "test-image:17"
bfs7.7.1 job 17: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs7.7.1/17/
bfs6.5.4 job 17: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4/17/

Change docker image naming convention for BFS6.5.4

---

Jenkinsfile

This PR fixes the naming convention of the docker image. In jenkins job number 17 for bfs7.7.1 and bfs 6.5.4, two separate jobs but with the same name "test-image:17" were concurrently ran. This caused failure in the node environment because the jenkins job for bfs7.7.1 and bfs6.5.4 was pointing to the same docker container "test-image:17"
bfs7.7.1 job 17: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs7.7.1/17/
bfs6.5.4 job 17: https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4/17/

Change docker image naming convention for BFS7.7.1

---

packages/kbn-config-schema/src/types/stream_type.test.ts
src/core/server/http/http_server.test.ts
src/core/server/http/router/validator/validator.test.ts
src/core/server/logging/appenders/file/file_appender.test.ts
src/plugins/console/public/application/models/sense_editor/__tests__/integration.test.js

This PR fixes files containing failing tests in Jenkins Unit Test stage...
- `src/core/server/http/router/validator/validator.test.ts`
>The error message that is changed in this file causes an error due to it being [provided by V8 and was upgraded in Node v12](https://github.com/nodejs/node/blob/6a349019da7ea79cd394101faad119db56b76bfa/deps/v8/src/common/message-template.h#L121-L122)
- `src/plugins/console/public/application/models/sense_editor/__tests__/integration.test.js`
This change is due to : 
> The internal algorithm used by Array.prototype.sort has changed in Node.js v11, and the sorting algorithm we use to sort terms is unfortunately not immune to the order in which Array.prototype.sort checks each element.
>
>In this case, the two terms are provided to the sort callback here as …

Fix for unit tests failing from node v12 update

---

package.json
yarn.lock

Integration Test Jenkins stage failing out/not completing due to
`(node:1231) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Node.js process-warning detected:
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`
The files where these errors occur are related to the node module `shot` which is no longer supported and has been moved to `@hapi/shot` which is compatible with Node v12.

Added @hapi/shot devDependency

---

package.json

- Removes `@hapi/shot` dependency as it is already a dependency of the installed module `@hapi/hapi` and is therefore not needed.
Refer to Issue #64

Remove @hapi/shot dependency as it is not needed

---

package.json
yarn.lock

- This reverts the addition of module `@hapi/shot` that is not needed as a dependency as the module `@hapi/hapi` has it as a devDependency.
- Adds `@hapi/hapi` module which updates its dependency `shot` to `@hapi/shot` thus fixing the `OutgoingMessage.prototype._headers` node deprecation warning. 
This will cause multiple errors in files that require in the old `hapi` module and will need to be fixed in a subsequent PR.

Remove @hapi/shot module & add @hapi/hapi module

---

Jenkinsfile

- Adds `build es`  & `build kbn` stages to jenkins pipeline
- This is due to these versions not being officially supported therefore there are no available download links thus we run our desired versions in an s3 bucket

Add build es & build kbn stages to jenkinsfile

---

Jenkinsfile

- Adds `Run ES` & `Run Kibana` stages to jenkinsfile
- These versions are not supported to must be installed via s3 bucket

Add run es & run kbn stages to 6.7.2

---

Jenkinsfile

- Adds `Integration Test` stage to Jenkinsfile 
- This runs with 2 reported failed tests in `src/cli/serve/integration_tests/reload_logging_config.test.js` resulting in an unstable build which will be fixed in the next PR

Add Integration Test stage to Jenkinsfile 

---

Jenkinsfile
src/server/saved_objects/serialization/index.ts

Currently, 20 unit tests fail. These failures are related to the following:
1. API call fails when invoking uuid.v1(). Error log: (https://jenkins.bfs.sichend.people.aws.dev/job/Kibana/job/bfs6.5.4_test/69/#showFailuresLink):
```
TypeError: Cannot read property 'v1' of undefined
146 |     const namespacePrefix =
147 |       namespace && !this.schema.isNamespaceAgnostic(type) ? `${namespace}:` : '';
> 148 |     return `${namespacePrefix}${type}:${id || uuid.v1()}`;
|                                                    ^
149 |   }
```
This PR refractors code according to [uuid documentation](https://github.com/uuidjs/uuid/blob/main/README.md#uuidv1options-buffer-offset). It first independently imports "v1" and calls the api as follows:  
```
import { v1 as uuidv1 } from 'uuid';
uuidv1();
``` …

Fix for failing unit test

---

test/functional/services/remote/leadfoot_command.js

This PR fixes two issue:
1. Current chrome version doesn't support node v8. This PR downgrades chrome to v79.
2. Chrome crashes when starting functional test stage. This PR fixes the issue by adding arguments to chromeOptions. 
Jenkins job: https://jenkins.bfs.sichend.people.aws.dev/blue/organizations/jenkins/Kibana/detail/bfs6.5.4_test/75/pipeline
Closes #111 and #94

Fix chrome issue

---

test/functional/services/remote/leadfoot_command.js

- Adds arguments to `chromeOptions`
- Commenting out `if (process.env.TEST_DISABLE_GPU)` conditional due to the crash continuing and `'disable-gpu'` being in the `chromeOptions`
- The Functional Test stage has not been added so in this state will not run. Once all errors causing stage to not initiate are fixed then the stage will be added in a subsequent PR along with the fixes.

Add chromeOptions arguments in browserOptions to fix Chrome failing

---

Jenkinsfile

- Removes `--no-optomize` flag from script in `Run Kibana` stage that caused kibana to refuse connections in the Functional Test stage
- The Functional Test stage has not been added so in this state will not run. Once all errors causing stage to not initiate are fixed then the stage will be added in a subsequent PR along with the fixes.
- Current error after this PR is detailed in issue #121

Fix Kibana script where kibana could not be connected to

---

Dockerfile
package.json

This PR contains 3 commits that together close issue #121. 
- It was decided to downgrade `chrome` to v79 and upgrade `chromedriver` to v79.  
- This version of chrome is no longer officially supported so downloading it from an s3 bucket was necessary
- The previous installation of `awscli` was incorrect and was therefore changed in the dockerfile.
- Functional Test stage has not been added yet and is being used for testing in jenkins (which the above test shows is running successfully). This is due to the Functional Test stage not running in parallel yet and thus taking around 2 hours. 
- The next steps will be to run the stage in parallel

Update chrome & chromedriver to v79

---

Jenkinsfile

Adds the `Functional Test` stage to jenkinsfile
- This will not run in parallel in its current state. Currently takes close to 4hrs to complete.
- Junit reporting file path is incorrect resulting in a failure for the stage even after it has fully completed and the results can be seen in the log.
- Will be updated to parallel & Junit path resolved in a subsequent PR.

Add Functional Test stage

---

Jenkinsfile

Changes the junit reporting script directory to fix junit report not showing in blue ocean. 
This test job has all but one of the functional tests suites removed for testing the script efficiently. This PR does not have those changes and therefore will show a report for all functional tests.

Fix junit reporting file script

---

Jenkinsfile

This adds the `Plugin Functional Test` stage to the jenkins pipeline.
https://github.com/Tengda-He/kibana/issues/130#issuecomment-1002723396

Add Plugin Functional Test stage

---

Jenkinsfile

Updates the jenkinsfile to run the Functional Test stage in parallel which saves close to 4 hours per job.

Make Functional Test stage run in parallel
